use capability;


db.questions.insertMany([
    {
        name: 'Understand',
        _id: 'PM-1',
        skillId:'PmStratPlan',
        text: 'How confident are you with Strategic Planning?',
        description: 'Researching, creating and bringing people and teams together on an aspirational vision to aligned to both I&Ws and the Group strategy & objectives',
        keyword: 'Strategic Planning',
    }, 

    {
        name: 'Understand',
        _id: 'PM-2',
        skillId:'PmStorytelling',
        text: 'How confident are you with Storytelling?',
        description: 'Ability to translate the vision & roadmap to capture the intended stakeholder group',
        keyword: 'Storytelling',
    }, 

    {
        name: 'Understand',
        _id: 'PM-3',
        skillId:'PmPropsExpertise',
        text: 'How confident are you with Propositional Expertise?',
        description: 'Ability to apply the understanding and knowledge of the I&W business, our customers, products to inform our Lab vision. Ability to apply the understanding of the I&W business, our customers and products to derive insights as to where there are opportunities to deliver customer value',
        keyword: 'Propositional Expertise',
    }, 

    {
        name: 'Understand',
        _id: 'PM-4',
        skillId:'PmHypothesisDef',
        text: 'How confident are you with Hypothesis Definition?',
        description: 'Ability to frame a statement with limited knowledge about a given situation that can be validated as true or false in order to find the best solution to a given problem ',
        keyword: 'Hypothesis Definition',
    }, 

    {
        name: 'Understand',
        _id: 'PM-5',
        skillId:'PmCustomerDiscoveryTechniques',
        text: 'How confident are you with Hypothesis Definition?',
        description: 'Ability to apply appropriate frameworks and techniques in order to develop a product or service that serves the needs, pain points, and challenges of our customers without bias',
        keyword: 'Customer Discovery Techniques',
    }, 
    {
        name: 'Understand',
        _id: 'PM-6',
        skillId:'PmOrgAwareness',
        text: 'How confident are you with Organisational Awareness?',
        description: 'Ability to apply the understanding of the I&W business model & blueprint to effectively synthesize and quality the research findings',
        keyword: 'Organisational Awareness',
    }, 

    {
        name: 'Understand',
        _id: 'PM-7',
        skillId:'PmMarketResearch',
        text: 'How confident are you with Market Research ?',
        description: 'Ability to gather relevant information on customers needs and preferences using appropriate tools and methods',
        keyword: 'Market Research',
    }, 
    {
        name: 'Understand',
        _id: 'PM-8',
        skillId:'PmSystemsThinking',
        text: 'How confident are you with Systems Thinking?',
        description: 'Ability to investigate what set of factors and interactions are contributing to an outcome',
        keyword: 'Systems Thinking',
    }, 

    {
        name: 'Understand',
        _id: 'PM-9',
        skillId:'PmCommSense',
        text: 'How confident are you with Commercial Sensibility?',
        description: 'Ability to apply the knowledge of the commercial drivers within I&W in order to track and manage the Lab costs appropriately',
        keyword: 'Commercial Sensibility',
    }, 

    {
        name: 'Understand',
        _id: 'PM-10',
        skillId:'PmCostBenAnalysis',
        text: 'How confident are you with Cost Benefit Analysis?',
        description: 'Ability to represent the cost to deliver change vs the anticipated benefit as a way to inform and prioritise what to do and in what order',
        keyword: 'Cost Benefit Analysis',
    }, 

    {
        name: 'Understand',
        _id: 'PM-11',
        skillId:'PmBudgetingPlanning',
        text: 'How confident are you with Budgeting & Planning?',
        description: 'Ability to effectively determine the budgetary requirements for the Lab based on the committed roadmap',
        keyword: 'Budgeting & Planning',
    }, 

    {
        name: 'Incubate',
        _id: 'PM-12',
        skillId:'PmOKRDef',
        text: 'How confident are you with OKR Definition?',
        description: 'Ability to apply the principles and practises of the OKR framework to create alignment and engagement for all teams in the Lab around measurable goals',
        keyword: 'OKR Definition',
    }, 
    {
        name: 'Incubate',
        _id: 'PM-13',
        skillId:'PmRoadmapDef',
        text: 'How confident are you with Roadmap Definition?',
        description: 'Ability to gather the relevant inputs to articulate the objectives and outcomes of the Lab to create alignment and buy-in across the teams and stakeholder groups',
        keyword: 'Roadmap Definition',
    }, 
    {
        name: 'Incubate',
        _id: 'PM-14',
        skillId:'PmStorytelling',
        text: 'How confident are you with Storytelling?',
        description: 'Ability to articulate to stakeholders both within and outside of the Lab as to what the Lab objectives and outcomes are, how we are planning to achieve them and progress we are making against those',
        keyword: 'Storytelling',
    }, 
    {
        name: 'Incubate',
        _id: 'PM-15',
        skillId:'PmPropsExpertise2',
        text: 'How confident are you with Propositional Expertise?',
        description: 'Ability to apply the understanding of the I&W business, our customers and products to ensure an aligned roadmap to our business OKRs.Ability to apply the understanding of the Insurance & Wealth business, our customers and products to ensure the product and features built provide the desired value.',
        keyword: 'Propositional Expertise',
    }, 
  
    {
        name: 'Incubate',
        _id: 'PM-16',
        skillId:'PmCustJourneyFW',
        text: 'How confident are you with Customer Journey Framework?',
        description: 'Ability to apply the Customer Journey Framework (GT specific) principles to shape, understand and manage our customer journeys',
        keyword: 'Customer Journey Framework',
    }, 
    {
        name: 'Incubate',
        _id: 'PM-17',
        skillId:'PmPersonaDef',
        text: 'How confident are you with Persona Definition?',
        description: 'Ability to apply relevant tools and practises to define an archetypical user of a system',
        keyword: 'Persona Definition',
    }, 
    {
        name: 'Incubate',
        _id: 'PM-18',
        skillId:'PmRiskMan',
        text: 'How confident are you with Risk Management?',
        description: 'Ability to apply tools and techniques (e.g. risk burndown, Risk Probability and Impact Matrix) to manage risks to the overall product / delivery',
        keyword: 'Risk Management',
    }, 
    {
        name: 'Incubate',
        _id: 'PM-19',
        skillId:'PmIssueMan',
        text: 'How confident are you with Issue Management?',
        description: 'Ability to determine when a task / work item becomes an issue and to effectively manage and triage to resolution following our guidelines',
        keyword: 'Issue Management',
    }, 
    {
        name: 'Incubate',
        _id: 'PM-20',
        skillId:'PmDependencyMan',
        text: 'How confident are you with Dependency Management?',
        description: 'Ability to identify, articulate and manage dependencies at a cross team and cross lab level ',
        keyword: 'Dependency Management',
    }, 
    {
        name: 'Incubate',
        _id: 'PM-21',
        skillId:'PmFinancialMan',
        text: 'How confident are you with Financial Management?',
        description: 'Ability to define, track and manage the capex and opex costs of the Lab',
        keyword: 'Financial Management',
    }, 

    {
        name: 'Develop',
        _id: 'PM-22',
        skillId:'PmPrioritisation',
        text: 'How confident are you with Prioritisation?',
        description: 'Ability to effectively apply prioritisation techniques (e.g RICE) to ensure the team understand and are able to focus on the right tasks at the right time',
        keyword: 'Prioritisation',
    }, 
    {
        name: 'Develop',
        _id: 'PM-23',
        skillId:'PmPlanning',
        text: 'How confident are you with Planning?',
        description: 'Ability to effectively apply planning techniques (e.g. story mapping) to create a holistic view for how everything fits together',
        keyword: 'Planning',
    }, 
    {
        name: 'Develop',
        _id: 'PM-24',
        skillId:'PmStorytelling3',
        text: 'How confident are you with Storytelling?',
        description: 'Ability to effectively communicate their respective backlog to team members, the Lab and stakeholders and how that aligns to the Lab OKRs',
        keyword: 'Storytelling',
    }, 
    {
        name: 'Develop',
        _id: 'PM-25',
        skillId:'PmJira',
        text: 'How confident are you with Jira?',
        description: 'Ability to use Jira functionality to manage and track the Lab and or team backlog',
        keyword: 'Jira',
    }, 
    {
        name: 'Develop',
        _id: 'PM-26',
        skillId:'PmGCP',
        text: 'How confident are you with GCP?',
        description: 'Ability to apply knowledge of GCP in order to understand how to accelerate the development of capabilities tied to our roadmap (e.g. data and analytics)',
        keyword: 'GCP',
    }, 
]);

db.skills.insertMany([
    {
        name: 'Strategic Planning',
        _id: 'PmStratPlan',
        disciplineId:'PM',
        optimusId: 'Understand',
    },
    {
        name: 'Storytelling',
        _id: 'PmStorytelling',
        disciplineId:'PM',
        optimusId: 'Understand',
    },
    {
        name: 'Propositional Expertise',
        _id: 'PmPropsExpertise',
        disciplineId:'PM',
        optimusId: 'Understand',
    },
    {
        name: 'Hypothesis Definition',
        _id: 'PmHypothesisDef',
        disciplineId:'PM',
        optimusId: 'Understand',
    },
    {
        name: 'Customer Discovery Techniques',
        _id: 'PmCustomerDiscoveryTechniques',
        disciplineId:'PM',
        optimusId: 'Understand',
    },
    {
        name: 'Organisational Awareness',
        _id: 'PmOrgAwareness',
        disciplineId:'PM',
        optimusId: 'Understand',
    },
    {
        name: 'Market Research',
        _id: 'PmMarketResearch',
        disciplineId:'PM',
        optimusId: 'Understand',
    },
    {
        name: 'Systems Thinking',
        _id: 'PmSystemsThinking',
        disciplineId:'PM',
        optimusId: 'Understand',
    },
    {
        name: 'Commercial Sensibility',
        _id: 'PmCommSense',
        disciplineId:'PM',
        optimusId: 'Understand',
    },
    {
        name: 'Cost Benefit Analysis',
        _id: 'PmCostBenAnalysis',
        disciplineId:'PM',
        optimusId: 'Understand',
    },
    {
        name: 'Budgeting & Planning',
        _id: 'PmBudgetingPlanning',
        disciplineId:'PM',
        optimusId: 'Understand',
    },
    {
        name: 'OKR Definition',
        _id: 'PmOKRDef',
        disciplineId:'PM',
        optimusId: 'Incubate',
    },
    {
        _id: 'PmRoadmapDef',
        disciplineId:'PM',
        optimusId: 'Incubate',
    },
    {
        name: 'Storytelling',
        _id: 'PmStorytelling2',
        disciplineId:'PM',
        optimusId: 'Incubate',
    },
    {
        name: 'Propositional Expertise',
        _id: 'PmPropsExpertise2',
        disciplineId:'PM',
        optimusId: 'Incubate',
    },
    {
        name: 'Customer Journey Framework',
        _id: 'PmCustJourneyFW',
        disciplineId:'PM',
        optimusId: 'Incubate',
    },
    {
        name: 'Persona Definition',
        _id: 'PmPersonaDef',
        disciplineId:'PM',
        optimusId: 'Incubate',
    },
    {
        name: 'Risk Management',
        _id: 'PmRiskMan',
        disciplineId:'PM',
        optimusId: 'Incubate',
    },
    {
        name: 'Issue Management',
        _id: 'PmIssueMan',
        disciplineId:'PM',
        optimusId: 'Incubate',
    },
    {
        name: 'Dependency Management',
        _id: 'PmDependencyMan',
        disciplineId:'PM',
        optimusId: 'Incubate',
    },
    {
        name: 'Financial Management',
        _id: 'PmFinancialMan',
        disciplineId:'PM',
        optimusId: 'Incubate',
    },
    {
        name: 'Prioritisation',
        _id: 'PmPrioritisation',
        disciplineId:'PM',
        optimusId: 'Develop',
    },
    {
        name: 'Planning',
        _id: 'PmPlanning',
        disciplineId:'PM',
        optimusId: 'Develop',
    },
    {
        name: 'Storytelling',
        _id: 'PmStorytelling3',
        disciplineId:'PM',
        optimusId: 'Develop',
    },
    {
        name: 'Jira',
        _id: 'PmJira',
        disciplineId:'PM',
        optimusId: 'Develop',
    },
    {
        name: 'GCP',
        _id: 'PmGCP',
        disciplineId:'PM',
        optimusId: 'Develop',
    },

]);