use capability;

db.dropDatabase();

db.questions.insertMany([
    {
        name: 'Understand',
        _id: 'question-1',
        skillId:'StratPlan',
        text: 'How confident are you with Strategic Planning?',
        description: 'Researching, creating and agreeing a vision to align actions, plans and people from an engineering perspective with I&W strategy & objectives',
        keyword: 'Strategic Planning',
    }, 
    {
        name: 'Understand',
        _id: 'question-2',
        skillId:'EnterpriseArch',
        text: 'How confident are you with Enterprise Architecture?',
        description: 'Ability to align I&W and the Labs technology strategy with our roadmap and documenting this using architectural models.\nAbility to shape the design of the target solution that is complementary to the overarching enterprise architecture principles and practices',
        keyword: 'Enterprise Architecture',
    },
    {
        name: 'Understand',
        _id: 'question-3',
        skillId:'EmergingTech',
        text: 'How confident are you with Emerging Technology Monitoring?',
        description: 'Identifying and assessing new and emerging technologies, products, services, methods and techniques.',
        keyword: 'Emerging Technology',
    },
    {
        name: 'Understand',
        _id: 'question-4',
        skillId:'OrgAwareness',
        text: 'How confident are you with Organisational Awarenesss?',
        description: 'Ability to apply the understanding of how we are set up as an I&W business, stakeholder landscape and our ways of working to ensure the solutions proposed are fit for purpose',
        keyword: 'Organisational Awareness',
    },
    {
        name: 'Understand',
        _id: 'question-5',
        skillId:'CommSense',
        text: 'How confident are you with Commercial Sensibility?',
        description: 'Awareness of the commercial model and mechanics of I&W and how to appropriately manage the spend of the Lab within those boundaries',
        keyword: 'Commercial Sensibility',
    },
    {
        name: 'Understand',
        _id: 'question-6',
        skillId:'FinanceModel',
        text: 'How confident are you with Financial Modelling?',
        description: 'Ability to represent numerical data in an effective way to understand past, present and future to support with decision making',
        keyword: 'Financial Modelling ',
    },
    {
        name: 'Understand',
        _id: 'question-7',
        skillId:'CostResourceEst',
        text: 'How confident are you with Cost & Resource Estimation?',
        description: 'Ability to effective plan and budget for persistent teams within the Lab aligned to the needs of the roadmap',
        keyword: 'Cost & Resource Estimation',
    },
     //////INCUBATE///////
    {
        name: 'Understand',
        _id: 'question-8',
        skillId:'Planning',
        text: 'How confident are you with Planning?',
        description: 'Ability to effectively translate the Lab roadmap into a quarterly plan that aligns to the budget allocated',
        keyword: 'Planning',
    },
    {
        name: 'Incubate',
        _id: 'question-9',
        skillId:'OKRDef',
        text: 'How confident are you with OKR Definition?',
        description: 'Ability to apply the OKR framework to create alignment and engagement around measurable goals',
        keyword: 'OKR Definition',
    },
    {
        name: 'Incubate',
        _id: 'question-10',
        skillId:'EnterpriseArch2',
        text: 'How confident are you with Enterprise Architecture?',
        description: 'Ability to apply the understanding of the I&W architecture (current and target) to define and articulate the engineering initiatives/epics required to deliver the Lab vision. Ability to define the to-be design while ensuring alignment with and adherence to the FP&R enterprise architecture principles and practices',
        keyword: 'Enterprise Architecture',
    },
    {
        name: 'Incubate',
        _id: 'question-11',
        skillId:'Storytelling',
        text: 'How confident are you with Storytelling?',
        description: 'Ability to articulate to stakeholders both within and outside of the Lab as to what the Lab objectives and outcomes are and how we are planning to achieve that',
        keyword: 'Storytelling',
    },
    
    {
        name: 'Incubate',
        _id: 'question-12',
        skillId:'PropsExpert',
        text: 'How confident are you with Propositional Expertise?',
        description: 'Ability to apply the understanding of the Insurance & Wealth business, our customers, products to derive insights as to where there opportunities for customer value',
        keyword: 'Propositional Expertise',
    },
    {
        name: 'Incubate',
        _id: 'question-13',
        skillId:'CustJourneyFW',
        text: 'How confident are you with the Customer Journey Framework?',
        description: 'Ability to apply the Customer Journey Framework (GT specific) principles to ensure the engineering related aspects take this into consideration',
        keyword: 'Customer Journey Framework',
    },
    {
        name: 'Incubate',
        _id: 'question-14',
        skillId:'SolutionArch',
        text: 'How confident are you with Solution Architecture?',
        description: 'Ability to define the technical solution and functional requirements to the specific customer / colleague needs identified',
        keyword: 'Solution Architecture',
    },
    {
        name: 'Incubate',
        _id: 'question-15',
        skillId:'SolutionDesign',
        text: 'How confident are you with Solution Design?',
        description: 'Ability to define, document and articulate the end to end design for a software solution',
        keyword: 'Solution Design',
    },
    {
        name: 'Incubate',
        _id: 'question-16',
        skillId:'FeasibileAssess',
        text: 'How confident are you with Feasibility Assessment?',
        description: 'Ability to define, evaluate and describe the change options for technical and business feasibility',
        keyword: 'Feasibility Assessment',
    },
    {
        name: 'Incubate',
        _id: 'question-17',
        skillId:'SecSolutionDesign',
        text: 'How confident are you with Security Solution Design?',
        description: 'Ability to define, document and articulate the end to end design for a security solution which is compliant with the Enterprise Architecture Security Standards and Patterns',
        keyword: 'Security Solution Design',
    },
    {
        name: 'Incubate',
        _id: 'question-18',
        skillId:'RequireAnalysis',
        text: 'How confident are you with Requirements Analysis?',
        description: 'Ability to elicit how the proposed solution is compliant with the Enterprise Architecture Security Standards and Patterns',
        keyword: 'Requirements Analysis',
    },
    {
        name: 'Incubate',
        _id: 'question-19',
        skillId:'AppSecurity',
        text: 'How confident are you with Application Security?',
        description: 'Ability to articulate the security features that need to be tested within an application to prevent security vulnerabilities in adherence with our standards',
        keyword: 'Application Security',
    },
    {
        name: 'Incubate',
        _id: 'question-20',
        skillId:'SecOps',
        text: 'How confident are you with Security Operations?',
        description: 'Ability to articulate the security operations methods and practises that required in the context of the security design in line with group standards ',
        keyword: 'Security Operations',
    },
    {
        name: 'Incubate',
        _id: 'question-21',
        skillId:'TestStratDev',
        text: 'How confident are you with Test Strategy Development?',
        description: 'Ability to define the testing guidelines and approach on what and how to test the target application(s) in line with group standards and practices',
        keyword: 'Test Strategy Development',
    },
    {
        name: 'Incubate',
        _id: 'question-22',
        skillId:'AutoTestFrameworks',
        text: 'How confident are you with Automated Testing Frameworks?',
        description: 'Ability to apply understanding of automated testing frameworks to shape and articulate what is most appropriate based on the initiative ',
        keyword: 'Automated Testing Frameworks',
    },
    {
        name: 'Incubate',
        _id: 'question-23',
        skillId:'InfoAssurance',
        text: 'How confident are you with Information Assurance?',
        description: 'Ability to articulate and apply appropriate methods and practices to protect against and manage risks relating to the use, storage and transmission of data',
        keyword: 'Information Assurance',
    },
    {
        name: 'Incubate',
        _id: 'question-24',
        skillId:'RiskMan',
        text: 'How confident are you with Risk Management?',
        description: 'Ability to apply tools and techniques (e.g. risk burndown, Risk Probability and Impact Matrix) to manage engineering risks related to the overall product / delivery',
        keyword: 'Risk Management',
    },
    
    {
        name: 'Incubate',
        _id: 'question-25',
        skillId:'IssueMan',
        text: 'How confident are you with Issue Management?',
        description: 'Ability to determine when a work item becomes an issue within the engineering domain and to effectively manage and triage following the required internal processes and tools',
        keyword: 'Issue Management',
    },
    
    {
        name: 'Incubate',
        _id: 'question-26',
        skillId:'DependencyMan',
        text: 'How confident are you with Dependency Management?',
        description: 'Ability to identify, articulate and manage dependencies from an engineering perspective at a cross team and cross lab level',
        keyword: 'Dependency Management',
    },
    
    {
        name: 'Incubate',
        _id: 'question-27',
        skillId:'Commsense2',
        text: 'How confident are you with Commercial sensibility?',
        description: 'Ability to apply the knowledge of the commercial construct and mechanics of I&W and how to appropriately manage the spend of the Lab within those boundaries',
        keyword: 'Commercial sensibility',
    },
    
    {
        name: 'Incubate',
        _id: 'question-28',
        skillId:'CostResourceEst2',
        text: 'How confident are you with Cost and Resource Estimation?',
        description: 'Ability to effectively model the cost and resource profile within the Lab to ensure persistency and stability',
        keyword: 'Cost & Resource Estimation',
    },

    //////Develop//////

    {
        name: 'Develop',
        _id: 'question-29',
        skillId:'Prioritisation',
        text: 'How confident are you with Prioritisation?',
        description: 'Ability to assess the value and effort of a given task to ensure alignment of priorities to that of the backlog',
        keyword: 'Prioritisation',
    },
    {
        name: 'Develop',
        _id: 'question-30',
        skillId:'Planning2',
        text: 'How confident are you with Planning?',
        description: 'Ability to apply relevant methods and practises to break down ',
        keyword: 'Planning',
    },
    {
        name: 'Develop',
        _id: 'question-31',
        skillId:'Storytelling2',
        text: 'How confident are you with Storytelling?',
        description: 'Ability to articulate what and the value of the technical initiatives / tasks that are required to deliver the requirements identified ',
        keyword: 'Storytelling',
    },
    {
        name: 'Develop',
        _id: 'question-32',
        skillId:'CodingPractices',
        text: 'How confident are you with Coding Practices?',
        description: 'Ability to apply knowledge and understanding of relevant coding practices to create cleaner, more readable, more efficient code with minimal errors',
        keyword: 'Coding Practices',
    },
    {
        name: 'Develop',
        _id: 'question-33',
        skillId:'SoftDesign',
        text: 'How confident are you with Software Design?',
        description: 'Ability to specify and design software to meet defined requirements by following agreed design standards and principles',
        keyword: 'Software Design',
    },
    {
        name: 'Develop',
        _id: 'question-34',
        skillId:'CodingQuality',
        text: 'How confident are you with Coding Quality ?',
        description: 'Ability to establish and define quality practices and be able to set up an environment in which to assess code quality',
        keyword: 'Coding Quality',
    },
    {
        name: 'Develop',
        _id: 'question-35',
        skillId:'CodeMan',
        text: 'How confident are you with Code Management?',
        description: 'Ability to apply source code best practices (e..g branching strategies) and setup and maintain source control repositories',
        keyword: 'Code Management',
    },
    {
        name: 'Develop',
        _id: 'question-36',
        skillId:'JS',
        text: 'How confident are you with Javascript?',
        description: '',
        keyword: 'Javascript',
    },
    {
        name: 'Develop',
        _id: 'question-37',
        skillId:'React',
        text: 'How confident are you with React?',
        description: '',
        keyword: 'React',
    },
    {
        name: 'Develop',
        _id: 'question-38',
        skillId:'ReactTestLib',
        text: 'How confident are you with React Testing Library?',
        description: '',
        keyword: 'React Testing Library',
    },
    {
        name: 'Develop',
        _id: 'question-39',
        skillId:'Typescript',
        text: 'How confident are you with Typescript?',
        description: '',
        keyword: 'Typescript',
    },
    {
        name: 'Develop',
        _id: 'question-40',
        skillId:'StyledComponents',
        text: 'How confident are you with Styled Components?',
        description: '',
        keyword: 'Styled Components',
    },
    {
        name: 'Develop',
        _id: 'question-41',
        skillId:'CSS',
        text: 'How confident are you with CSS?',
        description: '',
        keyword: 'CSS',
    },
    {
        name: 'Develop',
        _id: 'question-42',
        skillId:'Node',
        text: 'How confident are you with Node?',
        description: '',
        keyword: 'Node',
    },
    {
        name: 'Develop',
        _id: 'question-43',
        skillId:'Koa',
        text: 'How confident are you with Koa?',
        description: '',
        keyword: 'Koa',
    },
    {
        name: 'Develop',
        _id: 'question-44',
        skillId:'Supertest',
        text: 'How confident are you with Supertest?',
        description: '',
        keyword: 'Supertest',
    },
    {
        name: 'Develop',
        _id: 'question-45',
        skillId:'Nock',
        text: 'How confident are you with Nock?',
        description: '',
        keyword: 'Nock',
    },
    {
        name: 'Develop',
        _id: 'question-46',
        skillId:'Wiremock',
        text: 'How confident are you with Wiremock?',
        description: '',
        keyword: 'Wiremock',
    },
    {
        name: 'Develop',
        _id: 'question-47',
        skillId:'Git',
        text: 'How confident are you with Git?',
        description: '',
        keyword: 'Git',
    },
    {
        name: 'Develop',
        _id: 'question-48',
        skillId:'APITesting',
        text: 'How confident are you with API Testing?',
        description: 'Ability to use appropriate frameworks and tools to test the functionality, reliability, performance and security of APIs for which the Lab develops and is accountable for.',
        keyword: 'API Testing',
    },
    {
        name: 'Develop',
        _id: 'question-49',
        skillId:'PerformanceTesting',
        text: 'How confident are you with Performance Testing?',
        description: 'Ability to shape, run and document the outputs of our performance testing at each respective RTL stage',
        keyword: 'Performance Testing',
    },
    {
        name: 'Develop',
        _id: 'question-50',
        skillId:'Cypress',
        text: 'How confident are you with Cypress?',
        description: '',
        keyword: 'Cypress',
    },
    {
        name: 'Develop',
        _id: 'question-51',
        skillId:'Jest',
        text: 'How confident are you with Jest?',
        description: '',
        keyword: 'Jest',
    },
    {
        name: 'Develop',
        _id: 'question-52',
        skillId:'BurpSuite',
        text: 'How confident are you with Burp Suite?',
        description: '',
        keyword: 'Burp Suite',
    },
    {
        name: 'Develop',
        _id: 'question-53',
        skillId:'Jaws',
        text: 'How confident are you with Jaws?',
        description: '',
        keyword: 'Jaws',
    },
    {
        name: 'Develop',
        _id: 'question-54',
        skillId:'aXe',
        text: 'How confident are you with aXe?',
        description: '',
        keyword: 'aXe',
    },
    {
        name: 'Develop',
        _id: 'question-55',
        skillId:'DefectMan',
        text: 'How confident are you with Defect Management?',
        description: 'Ability to identify, assess, triage and resolve defects to minimise impact adhering to groups standards and practises',
        keyword: 'Defect Management',
    },
    {
        name: 'Develop',
        _id: 'question-56',
        skillId:'Docker',
        text: 'How confident are you with Docker?',
        description: '',
        keyword: 'Docker',
    },
    {
        name: 'Develop',
        _id: 'question-57',
        skillId:'Jenkins',
        text: 'How confident are you with Jenkins?',
        description: '',
        keyword: 'Jenkins',
    },
    {
        name: 'Develop',
        _id: 'question-58',
        skillId:'Kubernetes',
        text: 'How confident are you with Kubernetes?',
        description: '',
        keyword: 'Kubernetes',
    },
    {
        name: 'Develop',
        _id: 'question-59',
        skillId:'GCP',
        text: 'How confident are you with GCP?',
        description: 'Ability to apply knowledge and expertise of GCP to ensure successful migration from  ICP whilst meetings the needs of the Lab and respective teams. Ability to apply knowledge and experience of  GCP  in order to effectively navigate the route to live process in a safe, secure and efficient manner',
        keyword: 'GCP',
    },
   

]);

db.skills.insertMany([
        {
            name: 'Strategic Planning',
            _id: 'StratPlan',
            disciplineId:'SDev',
            optimusId: 'Understand',
        },
        {
            name: 'Enterprise Architecture',
            _id: 'EnterpriseArch',
            disciplineId:'SDev',
            optimusId: 'Understand',
        },
        {
            name: 'Emerging Technology Monitoring',
            _id: 'EmergingTech',
            disciplineId:'SDev',
            optimusId: 'Understand',
        },
        {
            name: 'Organisational Awareness',
            _id: 'OrgAwareness',
            disciplineId:'SDev',
            optimusId: 'Understand',
        },
        {
            name: 'Commercial Sensibility',
            _id: 'CommSense',
            disciplineId:'SDev',
            optimusId: 'Understand',
        },
        {
            name: 'Financial Modelling',
            _id: 'FinanceModel',
            disciplineId:'SDev',
            optimusId: 'Understand',
        },
        {
            name: 'Cost & Resource Estimation',
            _id: 'CostResourceEst',
            disciplineId:'SDev',
            optimusId: 'Understand',
        },
        {
            name: 'Planning',
            _id: 'Planning',
            disciplineId:'SDev',
            optimusId: 'Understand',
        },
        ///////INCUBATE//////////
        {
            name: 'OKR Definition',
            _id: 'OKRDef',
            disciplineId:'SDev',
            optimusId: 'Incubate',
        },
        {
            name: 'Enterprise Architecture',
            _id: 'EnterpriseArch2',
            disciplineId:'SDev',
            optimusId: 'Incubate',
        },
        {
            name: 'Storytelling',
            _id: 'Storytelling',
            disciplineId:'SDev',
            optimusId: 'Incubate',
        },
        {
            name: 'Propositional Expertise',
            _id: 'PropsExpert',
            disciplineId:'SDev',
            optimusId: 'Incubate',
        },
        {
            name: 'Customer Journey Framework',
            _id: 'CustJourneyFW',
            disciplineId:'SDev',
            optimusId: 'Incubate',
        },
        {
            name: 'Solution Architecture',
            _id: 'SolutionArch',
            disciplineId:'SDev',
            optimusId: 'Incubate',
        },
        {
            name: 'Solution Design',
            _id: 'SolutionDesign',
            disciplineId:'SDev',
            optimusId: 'Incubate',
        },
        {
            name: 'Feasibility Assessment',
            _id: 'FeasibileAssess',
            disciplineId:'SDev',
            optimusId: 'Incubate',
        },
        {
            name: 'Security Solution Design',
            _id: 'SecSolutionDesign',
            disciplineId:'SDev',
            optimusId: 'Incubate',
        },
        {
            name: 'Requirements Analysis',
            _id: 'RequireAnalysis',
            disciplineId:'SDev',
            optimusId: 'Incubate',
        },
        {
            name: 'Application Security',
            _id: 'AppSecurity',
            disciplineId:'SDev',
            optimusId: 'Incubate',
        },
        {
            name: 'Security Operations',
            _id: 'SecOps',
            disciplineId:'SDev',
            optimusId: 'Incubate',
        },
        {
            name: 'Test Strategy Development',
            _id: 'TestStratDev',
            disciplineId:'SDev',
            optimusId: 'Incubate',
        },
        {
            name: 'Automated Testing Frameworks',
            _id: 'AutoTestFrameworks',
            disciplineId:'SDev',
            optimusId: 'Incubate',
        },
        {
            name: 'Information Assurance',
            _id: 'InfoAssurance',
            disciplineId:'SDev',
            optimusId: 'Incubate',
        },
        {
            name: 'Risk Management',
            _id: 'RiskMan',
            disciplineId:'SDev',
            optimusId: 'Incubate',
        },
        {
            name: 'Issue Management',
            _id: 'IssueMan',
            disciplineId:'SDev',
            optimusId: 'Incubate',
        },
        {
            name: 'Dependency Management',
            _id: 'DependencyMan',
            disciplineId:'SDev',
            optimusId: 'Incubate',
        },
        {
            name: 'Commercial sensibility',
            _id: 'Commsense2',
            disciplineId:'SDev',
            optimusId: 'Incubate',
        },
        {
            name: 'Cost & Resource Estimation',
            _id: 'CostResourceEst2',
            disciplineId:'SDev',
            optimusId: 'Incubate',
        },

        ///////Develop////////
        {
            name: 'Prioritisation',
            _id: 'Prioritisation',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'Planning',
            _id: 'Planning2',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'Storytelling',
            _id: 'Storytelling2',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'Coding Practices',
            _id: 'CodingPractices',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'Software Design',
            _id: 'SoftDesign',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'Coding Quality',
            _id: 'CodingQuality',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'Code Management',
            _id: 'CodeMan',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'Javascript',
            _id: 'JS',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'React',
            _id: 'React',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'React Testing Library',
            _id: 'ReactTestLib',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'Typescript',
            _id: 'Typescript',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'Styled Components',
            _id: 'StyledComponents',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'CSS',
            _id: 'CSS',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'Node',
            _id: 'Node',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'Koa',
            _id: 'Koa',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'Supertest',
            _id: 'Supertest',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'Nock',
            _id: 'Nock',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'Wiremock',
            _id: 'Wiremock',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'Git',
            _id: 'Git',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'API Testing',
            _id: 'APITesting',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'Performance Testing',
            _id: 'PerformanceTesting',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'Cypress',
            _id: 'Cypress',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'Jest',
            _id: 'Jest',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'Burp Suite',
            _id: 'BurpSuite',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'Jaws',
            _id: 'Jaws',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'aXe',
            _id: 'aXe',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'Defect Management',
            _id: 'DefectMan',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'Docker',
            _id: 'Docker',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'Jenkins',
            _id: 'Jenkins',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'Kubernetes',
            _id: 'Kubernetes',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
        {
            name: 'Google Cloud Platform',
            _id: 'GCP',
            disciplineId:'SDev',
            optimusId: 'Develop',
        },
])


db.teams.insertMany([
    {
        _id: 'Ganon',
        name: 'Ganon',
    },
    {
        _id: 'Layton',
        name: 'Layton',
    },
    {
        _id: 'Link',
        name: 'Link',
    },
    {
        _id: 'MineSweep',
        name: 'Minesweeper',
    },
    {
        _id: 'NWoW',
        name: 'NWoW',
    },
    {
        _id: 'Pikachu',
        name: 'Pikachu',
    },
    {
        _id: 'QE',
        name: 'Quality Engineering',
    },
    {
        _id: 'Shield',
        name: 'S.H.I.E.L.D',
    },
    {
        _id: 'Sonic',
        name: 'Sonic',
    },
    {
        _id: 'Tetris',
        name: 'Tetris',
    },
    {
        _id: 'Thunderbirds',
        name: 'Thunderbirds',
    },
    {
        _id: 'Yoshi',
        name: 'Yoshi',
    },
    {
        _id: 'Starfox',
        name: 'Starfox',
    },
    {
        _id: 'N/A',
        name: 'N/A',
    },

]);

// db.users.insertMany([
//     {
//         _id: 'test@mail.com',
//         disciplineId: 'SDev',
//         teamId: 'Ganon',
//     },
// ]);

// db.answers.insertMany([
//     {
//         questionId: 'question-1',
//         userId: 'test@mail.com',
//         value: '100',
//     },
// ])